name: Integration Tests
on: push
jobs:
  go-tests:
    name: Run Go Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.20
          terraform_wrapper: false
      - name: Download Go Modules 1
        working-directory: test
        run: go get "github.com/gruntwork-io/terratest/modules/aws"
      - name: Download Go Modules 2
        working-directory: test
        run: go get "github.com/gruntwork-io/terratest/modules/terraform"
      - name: Download Go Modules 3
        working-directory: test
        run: go get "github.com/magiconair/properties/assert"
      - name: Run Go Tests
        working-directory: test
        run: go test -v 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}